service: Plantiful-app-api
app: plant-api
Globals:
    Api:
     Cors:
       AllowMethods: "*"
       AllowHeaders: "*"
       AllowOrigins: "*"

provider:
  name: aws
  runtime: nodejs14.x
  stage: v1
  region: us-east-1

functions:
  plantsAPI:
    handler: Controller/plants.handler
    events:
        - http:
            path: /health/
            method: get
        - http:
            path: /plant/add/
            method: put
        - http:
            path: /plants/
            method: get
          
        - http:
            path: plant/{plant}
            method: get
        - http:
            path: plants/{userplants}
            method: get
        - http:
            path: plant/delete/{userplants}/
            method: put
  UserAPI:
    handler: Controller/auth.handler
    events:
        - http:
            path: /auth/{id}
            method: get
        - http:
            path: /auth/register/
            method: post
        - http:
            path: /auth/login
            method: post
        - http:
            path: auth/update/{userid}
            method: put
        - http:
            path: auth/delete/{userid}
            method: delete
  Notification:
    handler: Controller/notification.handler
    events:
        - http:
            path: /notification/create
            method: post
        - http:
            path: /notification/cron-get/
            method: get
        - http:
            path: /notification/cron-update
            method: get
        - http:
            path: notification/watering/
            method: get
        - http:
            path: notification/status/update
            method: put
 
  SendGridEmail:
    handler: Email/mailServices.handler
    events:
         # Invoke Lambda function every minute
         # serverless.yml



      
plugins:
  - serverless-offline
  - serverless-dotenv-plugin